# Generated by Django 2.1.3 on 2019-01-04 16:39

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('param', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('oldprice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('url', models.URLField()),
                ('discount_image', imagekit.models.fields.ProcessedImageField(blank=True, max_length=250, upload_to='deals_images/%Y/%m')),
            ],
            options={
                'verbose_name': 'Скидка',
                'verbose_name_plural': 'Скидки',
            },
        ),
    ]
