# Generated by Django 2.1.3 on 2019-01-05 16:11

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0002_auto_20190105_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountproduct',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='discountproduct',
            name='param',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
