# Generated by Django 2.1.3 on 2019-01-05 16:12

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0003_auto_20190105_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountproduct',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='discountproduct',
            name='param',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
