# Generated by Django 2.1.3 on 2018-11-30 10:52

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendor',
            options={'ordering': ['name'], 'verbose_name': 'Бренд', 'verbose_name_plural': 'Бренды'},
        ),
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='product_images/%Y/%m'),
        ),
    ]
