# Generated by Django 2.1.3 on 2019-01-12 19:45

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='param',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True),
        ),
    ]
