# Generated by Django 2.1.3 on 2018-11-30 10:55

from django.db import migrations
import django.utils.timezone
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20181130_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=imagekit.models.fields.ProcessedImageField(default=django.utils.timezone.now, upload_to='product_images/%Y/%m'),
            preserve_default=False,
        ),
    ]
