# Generated by Django 2.1.3 on 2019-01-02 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20190101_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='discount',
            field=models.BooleanField(default=False),
        ),
    ]
