# Generated by Django 2.1.3 on 2019-01-13 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20190113_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='create',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
