# Generated by Django 2.1.3 on 2018-11-30 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20181130_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='oldprice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
