# Generated by Django 2.1.3 on 2019-01-16 13:51

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20190113_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, max_length=250, upload_to='category_images/%Y/%m'),
        ),
    ]
