# Generated by Django 2.1.3 on 2018-12-03 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20181202_1437'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('created',), 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AddField(
            model_name='comment',
            name='negativ',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='positiv',
            field=models.TextField(blank=True),
        ),
    ]
