# Generated by Django 2.1.3 on 2018-12-04 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20181203_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='negativ',
            field=models.TextField(blank=True, default='---'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='positiv',
            field=models.TextField(blank=True, default='---'),
        ),
    ]
