# Generated by Django 2.1.3 on 2018-12-04 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20181204_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='negativ',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='positiv',
            field=models.TextField(blank=True),
        ),
    ]
