# Generated by Django 2.1.3 on 2018-12-04 19:41

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20181204_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='characteristic',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
