# Generated by Django 2.1.3 on 2018-12-16 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20181204_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='characteristic',
            field=models.TextField(blank=True, null=True),
        ),
    ]
