# Generated by Django 2.1.3 on 2018-12-16 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20181216_1645'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='characteristic',
            new_name='param',
        ),
    ]
